project:
  type: book
  output-dir: docs

book:
  title: "Bootcamp 2023"
  author: "KNUM ATLAS"
  date: "October 2023"
  date-format: "MMMM YYYY"
  sidebar:
    style: docked
    search: true
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_regresja.qmd
    - 3_klasyfikacja.qmd
#     - references.qmd
# 
# bibliography: references.bib

format:
  html:
    theme:
      light: pulse
      dark: darkly
  pdf:
    documentclass: scrreprt





